### ISSUE TITLE
ends before my version

### ISSUE THREAD

**Issue by csprance** [entradainteractive/miscreated-localization#2]
@Amoebawp Can you please describe a little more about what the issue you're seeing is

**Comment by Amoebawp** [comment]
item.xml misses this part at its end to open it with excel :

`  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <PageSetup>
    <Header x:Margin="0.3"/>
    <Footer x:Margin="0.3"/>
    <PageMargins x:Bottom="0.75" x:Left="0.7" x:Right="0.7" x:Top="0.75"/>
   </PageSetup>
   <Unsynced/>
   <Print>
    <ValidPrinterInfo/>
    <PaperSizeIndex>9</PaperSizeIndex>
    <HorizontalResolution>600</HorizontalResolution>
    <VerticalResolution>600</VerticalResolution>
   </Print>
   <Selected/>
   <TopRowVisible>3</TopRowVisible>
   <Panes>
    <Pane>
     <Number>3</Number>
     <ActiveRow>26</ActiveRow>
     <ActiveCol>2</ActiveCol>
    </Pane>
   </Panes>
   <ProtectObjects>False</ProtectObjects>
   <ProtectScenarios>False</ProtectScenarios>
  </WorksheetOptions>
 </Worksheet>
</Workbook>`

**Comment by Amoebawp** [comment]
Hello @csprance,
I'm terribly sorry, i left you in the middle of the conversation, had a pretty busy time off.
Thank you for fixing that though, everything works fine on my end now.
Will get back to you asap with a translated version.
Thanks again
Pitiviers.
